### PR TITLE
Tidy-up LXPolkit widget alignments.

### PR DESCRIPTION
**Pull request by ZanderBrown**
User Selector & Password Entry sizes are linked

User Selector Label & Request Label sizes ares linked and are aligned left

Icon is shown above the request title to stop the dialog becoming excessively wide

### CODE REVIEW

**Comment by ZanderBrown** [comment]
@lxde any thoughts?

**Comment by ZanderBrown** [comment]
Anyone?

**Comment by LStranger** [comment]
Looks OK but what kind of problem will this change fix?

**Comment by ZanderBrown** [comment]
Wow this was a while ago

From what I remember it takes the current layout which looks something like so

```
[icon]          [message]
[icon]
User: [selector                   ]
Password: [entry                  ]
```

Which is a bit all over the place and aligns the items
```
[icon]
[icon]
[message]
User:     [selector               ]
Password: [entry                  ]

**Comment by LStranger** [comment]
OK. Let it be. Thank you.

**Pull request merged**
