### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by aldatsa**
Hi,
I found and fixed some typos while I was translating lxsession to Basque:
assiociate -> associate
utilty -> utility
transpacency -> transparency

### CODE REVIEW

**Comment by luis-pereira** [comment]
@aldatsa Squash it, pls

**Comment by aldatsa** [comment]
Done!

**Comment by luis-pereira** [comment]
Hummm Just realized that this is lxsession not lxqt-session.
@jleclanche @PCMan @paulolieuthier Why do we have lxession here ?

**Comment by paulolieuthier** [comment]
@luis-pereira good question. We also have lxterminal.

**Comment by aldatsa** [comment]
lxsession is in the LXDE pootle server:
http://pootle.lxde.org/eu/lxsession/
Should I continue translating it?

**Comment by luis-pereira** [comment]
@aldatsa lxsession is part of the LXDE project, **not** LXQt. If you want to contribute to the LXQt project, lxsession and lxtermimal aren't part of it.

**Comment by aldatsa** [comment]
Ok, no problem, I want to contribute Basque translations to both LXQt and LXDE

**Comment by jleclanche** [comment]
Sorry, I'm working through the github backlog. I'm in May now!

We have lxsession because we used to use it in LXQt and @gilir agreed to move it here.

@gilir This is yours but gtm.

**Pull request merged**
